version: "3.2"
services:

  nginx:
    image: nginx:1.14.2
    ports:
    - "80:80"
    - "443:443"
    links:
    - "php7.0"
    volumes:
    - ../:/datadisk/website/
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
    - ./conf/vhost/:/etc/nginx/vhost/
    container_name: nginx
    networks:
      lnmp:
        ipv4_address: 192.168.100.10

  mysql:
    image: mysql:5.6.43
    ports:
    - "3306:3306"
    expose:
    - "3306"
    volumes:
    - ../:/datadisk/website
    - ./conf/mysql/my5.6.cnf:/etc/mysql/my.cnf
    - ./runtime/mysql5.6/:/var/lib/mysql/
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    container_name: mysql
    networks:
      lnmp:
        ipv4_address: 192.168.100.30

  redis:
    image: redis:5.0.3
    ports:
    - "6379:6379"
    expose:
    - "6379"
    volumes:
    - ../:/datadisk/website
    - ./conf/redis.conf:/etc/redis.conf
    command: "redis-server /etc/redis.conf"

    container_name: redis
    networks:
      lnmp:
        ipv4_address: 192.168.100.40


  php7.0:
    image: netrope/php7.0_ext:1.0
    links:
    - "redis"
    - "mysql"
    volumes:
    - ../:/datadisk/website
    - ./conf/php7.0/php.ini:/usr/local/etc/php/php.ini
    - ./conf/php7.0/php-fpm.conf:/usr/local/etc/php-fpm.conf
    container_name: php7.0
    networks:
      lnmp:
        ipv4_address: 192.168.100.20

#  memcache:
#    image: memcached:1.5.11
#    ports:
#    - "11211:11211"
#    expose:
#    - "11211"
#    volumes:
#    - ../:/datadisk/website
#    container_name: memcached
#    networks:
#      lnmp:
#        ipv4_address: 192.168.100.60

#  mongodb:
#    image: mongo:4.0.3
#    ports:
#    - "27017:27017"
#    expose:
#    - "27017"
#    volumes:
#    - ../:/datadisk/website
#    - ./conf/mongod.conf:/etc/mongod.conf
#    command: "mongod --config /etc/mongod.conf"
#    container_name: mongodb
#    networks:
#      lnmp:
#        ipv4_address: 192.168.100.70

#  rabbitmq:
#    image: rabbitmq:3.7.8
#    ports:
#    - "4369:4369"
#    - "5672:5672"
#    - "15672:15672"
#    - "25672:25672"
#    expose:
#    - "4369"
#    - "5672"
#    - "15672"
#    - "25672"
#    volumes:
#    - ../:/datadisk/website
#    - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
#    container_name: rabbitmq
#    networks:
#      lnmp:
#        ipv4_address: 192.168.100.80

networks:
  lnmp:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.100.0/24
