version: "3"
services:

#  nginx:
#      image: nginx:1.13.8
#      ports:
#        - "80:80"
#        - "443:443"
#      links:
#        - "php7.2"
#      volumes:
#        - ./conf/nginx.conf:/etc/nginx/nginx.conf
#        - ./conf/vhost/:/etc/nginx/vhost/
#        - ../:/datadisk/website/
#      container_name: nginx
#
#  mysql:
#      image: mysql:5.7.21
#      ports:
#        - "3306:3306"
#      expose:
#        - "3306"
#      volumes:
#        - ./conf/my.cnf:/etc/mysql/my.cnf
#        - ../:/datadisk/website
#
#      environment:
#        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#      container_name: mysql
#
#
#  redis:
#      image: redis:4.0.8
#      ports:
#        - "6379:6379"
#      expose:
#        - "6379"
#      volumes:
#        - ./conf/redis.conf:/etc/redis.conf
#        - ../:/datadisk/website
#      command: "redis-server /etc/redis.conf"
#
#      container_name: redis

  #php7.2:
  #    image: php:7.2.1-fpm
  #    expose:
  #      - "9000"
  #    links:
  #      - "redis"
  #      - "mysql"
  #    volumes:
  #      - ./conf/php7.2/php.ini:/usr/local/etc/php/php.ini
  #      - ./conf/php7.2/php-fpm.conf:/usr/local/etc/php-fpm.conf
  #      - ./conf/php7.2/php-fpm.d/:/usr/local/etc/php-fpm.d/
  #      - ./conf/php7.2/extensions/:/usr/local/lib/php/extensions/
  #      - ../:/datadisk/website
  #    container_name: php7.2


  php7.2:
      image: netrope/php:7.2
      expose:
        - "9000"
#      links:
#        - "redis"
#        - "mysql"
      command:
        ["/sbin/init"]
      volumes:
        - ./conf/php7.2/php.ini:/usr/local/php7/etc/php.ini
        - ./conf/php7.2/php-fpm.conf:/usr/local/php7/etc/php-fpm.conf
        - ./conf/php7.2/php-fpm.d/:/usr/local/php7/etc/php-fpm.d/
  #      - ./conf/php7.2/extensions/:/usr/local/lib/php/extensions/
        - ../:/datadisk/website
      container_name: php7.2
  #    entrypoint: ["/usr/sbin/init"]
  #    entrypoint: /bin/echo
      entrypoint:
#        - /sbin/init
        - /usr/local/php7/sbin/php-fpm
#        - -D
#        - -y
#        - /usr/local/php7/etc/php-fpm.conf
