version: "3.2"
services:

  nginx:
    image: nginx:1.13.8
    ports:
    - "80:80"
    - "443:443"
    links:
    - "php7.2"
    - "php5.6"
    volumes:
    - ../:/datadisk/website/
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
    - ./conf/vhost/:/etc/nginx/vhost/
    - ./runtime/logs:/log
    container_name: nginx
    networks:
      lnmp:
        ipv4_address: 192.168.100.10

  mysql:
    # image: mysql:5.7.21
    image: mysql:5.5.60
    ports:
    - "3306:3306"
    expose:
    - "3306"
    volumes:
    - ../:/datadisk/website
    - ./runtime/logs:/log

#    - ./conf/my.cnf/my5.7.cnf:/etc/mysql/my5.7.cnf
#    - ./runtime/mysql5.7/:/var/lib/mysql/
    - ./conf/my.cnf/my5.5.cnf:/etc/mysql/my5.5.cnf
    - ./runtime/mysql5.5/:/var/lib/mysql/

    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    container_name: mysql
    networks:
      lnmp:
        ipv4_address: 192.168.100.30

  redis:
    image: redis:4.0.8
    ports:
    - "6379:6379"
    expose:
    - "6379"
    volumes:
    - ../:/datadisk/website
    - ./conf/redis.conf:/etc/redis.conf
    - ./runtime/logs:/log
    command: "redis-server /etc/redis.conf"

    container_name: redis
    networks:
      lnmp:
        ipv4_address: 192.168.100.40


  php7.2:
    build: ./php7.2/
    links:
    - "redis"
    - "mysql"
    volumes:
    - ../:/datadisk/website
    - ./runtime/logs:/log
    - ./php7.2/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    container_name: php7.2
    networks:
      lnmp:
        ipv4_address: 192.168.100.20

  php5.6:
    build: ./php5.6/
    links:
    - "redis"
    - "mysql"
    volumes:
    - ../:/datadisk/website
    - ./runtime/logs:/log
#    - ../meitu_local_config/:/www/privdata/
    - ./php5.6/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    container_name: php5.6
    networks:
      lnmp:
        ipv4_address: 192.168.100.50

  memcache:
    image: memcached:1.5.11
    ports:
    - "11211:11211"
    expose:
    - "11211"
    volumes:
    - ../:/datadisk/website
    - ./runtime/logs:/log
    container_name: memcached
    networks:
      lnmp:
        ipv4_address: 192.168.100.60

  mongodb:
    image: mongo:4.0.3
    ports:
    - "27017:27017"
    expose:
    - "27017"
    volumes:
    - ../:/datadisk/website
    - ./conf/mongod.conf:/etc/mongod.conf
    - ./runtime/logs:/var/log
    - ./runtime/mongodb:/var/lib/mongodb
    command: "mongod --config /etc/mongod.conf"
    container_name: mongodb
    networks:
      lnmp:
        ipv4_address: 192.168.100.70

  rabbitmq:
    image: rabbitmq:3.7.8
    ports:
    - "4369:4369"
    - "5672:5672"
    - "15672:15672"
    - "25672:25672"
    expose:
    - "4369"
    - "5672"
    - "15672"
    - "25672"
    volumes:
    - ../:/datadisk/website
    - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
#    - ./runtime/logs:/var/log
#    - ./runtime/mongodb:/var/lib/mongodb
    container_name: rabbitmq
    networks:
      lnmp:
        ipv4_address: 192.168.100.80

networks:
  lnmp:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.100.0/24
