nginx:
    image: nginx:1.13.8
    ports:
      - "80:80"
      - "443:443"
    links:
      - "php7.2"
    volumes:
      - /datadisk/docker-lnmp/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /datadisk/:/datadisk/
    links:
      - "php7.2"
    container_name: nginx

mysql:
    image: mysql:5.7.21
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - /datadisk/docker-lnmp/mysql/my.cnf:/etc/mysql/my.cnf
      - /datadisk/:/datadisk/

    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    container_name: mysql

php7.2:
    image: php:7.2.1-fpm
    expose:
      - "9000"
    links:
      - "redis"
      - "mysql"
    volumes:
      - /datadisk/:/datadisk/
    container_name: php7.2

redis:
    image: redis:4.0.8
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - /datadisk/docker-lnmp/redis/redis.conf:/etc/redis.conf
      - /datadisk/:/datadisk/
    command: "redis-server /etc/redis.conf"

    container_name: redis
