#!/bin/bash
    #-v /datadisk/website/docker-lnmp/conf/php7.2/php-fpm.d/:/usr/local/php7/etc/php-fpm.d/ \

docker run -tid --name my  \
    -v /datadisk/:/datadisk/ \
    -v /datadisk/website/docker-lnmp/conf/php7.2/php.ini:/usr/local/php7/etc/php.ini \
    -v /datadisk/website/docker-lnmp/conf/php7.2/php-fpm.conf:/usr/local/php7/etc/php-fpm.conf \
     netrope/php-fpm:7.2